import { buildHighRiskDisagreementAssessment } from "@/lib/audits/workflow";

describe("high-risk disagreement assessment", () => {
  it("auto-triggers second review for sponsor-facing files with weak support and open proof gaps", () => {
    const assessment = buildHighRiskDisagreementAssessment({
      audit: {
        candidateId: "candidate_1",
        displayName: "Maya Rios",
        displayHeadline: "Climate operator",
        displayRegion: "Oakland, CA",
        actualRegion: "Oakland, CA",
        stage: "SPONSOR_OUTREACH",
        reviewState: "flagged",
        readinessScore: 49,
        artifactCount: 2,
        claimCount: 3,
        evidenceDepth: "Thin proof set",
        thirdPartyArtifactCount: 0,
        supportCoverage: 61,
        missingProofCount: 3,
        cautionFlagCount: 2,
        memoStatus: "READY",
        systemDecision: "hold",
        systemRationale: "The evidence file is still too thin for outreach.",
        humanDecision: "advance",
        humanDecisionSummary: "Advance now",
        humanDecisionRationale: "The operator wants to push the file forward.",
        humanDecidedById: "user_1",
        humanDecidedByName: "Ada Sponsor",
        humanDecisionAt: new Date("2026-03-01T00:00:00.000Z"),
        disagreementDirection: "human_more_optimistic",
        hasDisagreement: true,
      },
      safetyReport: {
        decision: "hold",
        rationale: "The evidence file is still too thin for outreach.",
        missingProof: [
          "Add one clearer example of leadership or ownership over other people or systems.",
          "Add third-party corroboration from a mentor, manager, or partner.",
          "Refresh the file with newer proof so the case is not leaning on stale evidence.",
        ],
        cautionFlags: ["Proof is still thin."],
        supportCoverage: 61,
        citationCoverage: 33,
        unsupportedStatements: ["Maya led a nationally recognized network."],
        uncitedStatements: ["The file is still too thin for outreach."],
        invalidCitations: [],
        supportedStatements: 2,
        citedStatements: 1,
        uncitedStatementCount: 2,
        invalidCitationCount: 0,
        internalContactDetails: [],
        sponsorFacingContactDetails: [],
        internalContactDetailCount: 0,
        sponsorFacingContactDetailCount: 0,
        totalStatements: 3,
        potentialContradictions: ["One artifact implies a local pilot while another suggests multi-city rollout."],
        blockingContradictions: [],
        thirdPartyArtifactCount: 0,
        staleArtifactCount: 1,
        oldestArtifactAgeDays: 480,
        duplicateClaimCount: 0,
        evidenceFreshnessScore: 3.8,
        sourceQualityScore: 4.7,
        unsupportedNarrativeGroups: ["Executive summary"],
      },
      openProofRequestCount: 2,
    });

    expect(assessment.shouldTrigger).toBe(true);
    expect(assessment.riskScore).toBeGreaterThanOrEqual(6);
    expect(assessment.reason).toContain("more optimistic");
  });

  it("does not auto-trigger when the disagreement is mild and the evidence file is healthy", () => {
    const assessment = buildHighRiskDisagreementAssessment({
      audit: {
        candidateId: "candidate_2",
        displayName: "Leila Mensah",
        displayHeadline: "Systems builder",
        displayRegion: "Accra, Ghana",
        actualRegion: "Accra, Ghana",
        stage: "REVIEW",
        reviewState: "approved",
        readinessScore: 74,
        artifactCount: 5,
        claimCount: 8,
        evidenceDepth: "Deep proof set",
        thirdPartyArtifactCount: 2,
        supportCoverage: 93,
        missingProofCount: 0,
        cautionFlagCount: 0,
        memoStatus: "READY",
        systemDecision: "advance",
        systemRationale: "The evidence file is strong enough to move.",
        humanDecision: "hold",
        humanDecisionSummary: "Stay deliberate",
        humanDecisionRationale: "Wait one more week before outreach.",
        humanDecidedById: "user_2",
        humanDecidedByName: "Review Lead",
        humanDecisionAt: new Date("2026-03-02T00:00:00.000Z"),
        disagreementDirection: "system_more_optimistic",
        hasDisagreement: true,
      },
      safetyReport: {
        decision: "advance",
        rationale: "The evidence file is strong enough to move.",
        missingProof: [],
        cautionFlags: [],
        supportCoverage: 93,
        citationCoverage: 75,
        unsupportedStatements: [],
        uncitedStatements: [],
        invalidCitations: [],
        supportedStatements: 4,
        citedStatements: 3,
        uncitedStatementCount: 1,
        invalidCitationCount: 0,
        internalContactDetails: [],
        sponsorFacingContactDetails: [],
        internalContactDetailCount: 0,
        sponsorFacingContactDetailCount: 0,
        totalStatements: 4,
        potentialContradictions: [],
        blockingContradictions: [],
        thirdPartyArtifactCount: 2,
        staleArtifactCount: 0,
        oldestArtifactAgeDays: 42,
        duplicateClaimCount: 0,
        evidenceFreshnessScore: 8.7,
        sourceQualityScore: 8.4,
        unsupportedNarrativeGroups: [],
      },
      openProofRequestCount: 0,
    });

    expect(assessment.shouldTrigger).toBe(false);
    expect(assessment.riskScore).toBeLessThan(6);
    expect(assessment.reason).toBeNull();
  });
});
